# Generated by Django 2.2.4 on 2020-11-29 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departmanlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departman', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='talep_detayi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adsoyad', models.CharField(max_length=20, null=True)),
                ('konu', models.CharField(max_length=100)),
                ('öncelik', models.CharField(choices=[('Düşük', 'Düşük'), ('Orta', 'Orta'), ('Yüksek', 'Yüksek')], max_length=10)),
                ('içerik', models.TextField(max_length=500)),
                ('departman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.departmanlar')),
            ],
        ),
    ]
