# Generated by Django 2.2.4 on 2020-11-29 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talep_detayi',
            name='adsoyad',
        ),
    ]
