# Generated by Django 3.1.3 on 2020-11-30 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0002_remove_talep_detayi_adsoyad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talep_detayi',
            old_name='içerik',
            new_name='icerik',
        ),
        migrations.RenameField(
            model_name='talep_detayi',
            old_name='öncelik',
            new_name='oncelik',
        ),
        migrations.AddField(
            model_name='talep_detayi',
            name='adsoyad',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
